baseURL = "https://harshadss.github.io/"
languageCode = "en-us"
title = "Harshad Saykhedkar"
theme = "hugo-theme-nix"

[params]
    Name = "Harshad Saykhedkar"
    HeaderUsername = "harshad"
    HeaderHostname = "foundation"
    About = "Harshad Saykhedkar, Personal Website and Blog. Ramblings about AI, Coding, ML, STEM, books and what not."
    TwitterID = "harshad_geek"

[menu]

    [[menu.header]]
      name = "blog"
      weight = 1
      url = "/posts"

    [[menu.header]]
      parent = "blog"
      name = "All"
      url = "/posts"

    [[menu.header]]
      parent = "blog"
      name = "Tags"
      url = "/tags"
